CREATE TABLE pageInfo (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    logo VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
) ENGINE=InnoDB;


CREATE TABLE navigations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    hashTag VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE subNavigations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    hashTag VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE editHeadingTexts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    h1 VARCHAR(255) NOT NULL,
    playButtonLink VARCHAR(255) NOT NULL,
    subH1 VARCHAR(255) NOT NULL,
    getStartedLink VARCHAR(255) NOT NULL,
    headingMessageText TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE headingSlideContainers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    iconImage VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    clickRedir VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE whoWeAreComponent (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    heading VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    buttonText VARCHAR(255) NOT NULL,
    clickRedir VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE OurInfo (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    YearsOfExperience VARCHAR(255) NOT NULL,
    talentedTeam VARCHAR(255) NOT NULL,
    projectsDelivered VARCHAR(255) NOT NULL,
    countriesServed VARCHAR(255) NOT NULL
) ENGINE=InnoDB;


CREATE TABLE ServicesWeProvide (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    heading VARCHAR(255) NOT NULL,
    subHeading VARCHAR(255) NOT NULL
) ENGINE=InnoDB;


CREATE TABLE Technologies (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    icon VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE LatestProjects (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    heading VARCHAR(255) NOT NULL,
    subHeading VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE LatestProjectsList (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    image VARCHAR(255) NOT NULL,
    heading VARCHAR(255) NOT NULL,
    subHeading VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE BusinessInfoImage (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    heading VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    image VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE BusinessInfoList (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    text TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE GetSolutionText (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    heading VARCHAR(255) NOT NULL,
    text TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE GetSolutionTextList (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    text TEXT NOT NULL,
    percent VARCHAR(10) NOT NULL,
    color VARCHAR(20) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE GetSolutionTextList (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    text TEXT NOT NULL,
    percent VARCHAR(10) NOT NULL,
    color VARCHAR(20) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE GetSolutionTextCard (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    image VARCHAR(255) NOT NULL,
    heading VARCHAR(255) NOT NULL,
    subHeading VARCHAR(255) NOT NULL,
    personImage VARCHAR(255) NOT NULL,
    personName VARCHAR(255) NOT NULL,
    personRole VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE workedIn (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    icon VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE whoWeAre (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    image VARCHAR(255) NOT NULL,
    heading VARCHAR(255) NOT NULL,
    message TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE reviewsAndFeedBacks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,
    occupation VARCHAR(255) NOT NULL,
    review TEXT NOT NULL,
    platform VARCHAR(255) NOT NULL,
    stars VARCHAR(10) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE readMore (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    TrustpilotReviewLink VARCHAR(255) NOT NULL,
    ClutchReviewLink VARCHAR(255) NOT NULL,
    appStoreReviewLink VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE footer (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    heading VARCHAR(255) NOT NULL,
    subHeading VARCHAR(255) NOT NULL,
    facebookLink VARCHAR(255) NOT NULL,
    twitterLink VARCHAR(255) NOT NULL,
    youtubeLink VARCHAR(255) NOT NULL,
    linkedInLink VARCHAR(255) NOT NULL,
    instagramLink VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE footerCompanyLinks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    link VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE footerTechnologiesLinks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    link VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE footerOurServicesLinks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    link VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
